QUE : 1 -->

Install TensorFlow and Keras in your Python environment, then write a script to create a simple 2-layer neural network (input, hidden, output) using Keras' Sequential API.

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the Sequential model
model = Sequential()

# Hidden layer
model.add(Dense(16, activation='relu', input_shape=(4,)))

# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Display model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

QUE : 2 -->

Given a simple neural network with one hidden layer (using Keras), print out the weights before and after one training step on dummy data to observe how the weight update rule works.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Dummy training data
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=np.float32)

# Dummy labels (OR gate)
y = np.array([0, 1, 1, 1], dtype=np.float32)

# Create a simple neural network
model = Sequential([
    Dense(4, activation='relu', input_shape=(2,), name='Hidden_Layer'),
    Dense(1, activation='sigmoid', name='Output_Layer')
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Build the model
model.build()

# Print weights before training
print("========== WEIGHTS BEFORE TRAINING ==========")
for layer in model.layers:
    weights, biases = layer.get_weights()
    print(f"\nLayer: {layer.name}")
    print("Weights:")
    print(weights)
    print("Biases:")
    print(biases)

# Perform ONE training step
model.fit(X, y, epochs=1, batch_size=4, verbose=0)

# Print weights after training
print("\n========== WEIGHTS AFTER ONE TRAINING STEP ==========")
for layer in model.layers:
    weights, biases = layer.get_weights()
    print(f"\nLayer: {layer.name}")
    print("Weights:")
    print(weights)
    print("Biases:")
    print(biases)

c:\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


========== WEIGHTS BEFORE TRAINING ==========

Layer: Hidden_Layer
Weights:
[[ 0.30436373 -0.0841763   0.7764082   0.33218622]
 [ 0.61662674 -0.8949897   0.9625387   0.65979123]]
Biases:
[0. 0. 0. 0.]

Layer: Output_Layer
Weights:
[[ 0.4618051 ]
 [ 0.9759488 ]
 [-0.35535347]
 [ 0.35117733]]
Biases:
[0.]

========== WEIGHTS AFTER ONE TRAINING STEP ==========

Layer: Hidden_Layer
Weights:
[[ 0.30536368 -0.0841763   0.77540827  0.33318618]
 [ 0.6176267  -0.8949897   0.9615388   0.66079116]]
Biases:
[ 0.00099997  0.         -0.00099997  0.00099997]

Layer: Output_Layer
Weights:
[[ 0.4628051 ]
 [ 0.9759488 ]
 [-0.3543535 ]
 [ 0.35217732]]
Biases:
[0.00099998]


QUE : 3 -->

Manually calculate the gradient of the loss with respect to the weights for a single neuron using the chain rule, given these values: input x=2, weight w=0.5, bias b=1, activation=sigmoid, target y=1.Hint: Write out each step of the derivative using the chain rule, then compute the numeric value.


# Manual Gradient Calculation Using the Chain Rule

**Given:**

* Input: (x = 2)
* Weight: (w = 0.5)
* Bias: (b = 1)
* Activation: Sigmoid
* Target: (y = 1)

### Step 1: Compute the neuron's output

The weighted sum is:

[
z = wx + b
]

Substitute the values:

[
z = (0.5)(2) + 1 = 2
]

The sigmoid activation is:

[
\hat{y} = \sigma(z) = \frac{1}{1+e^{-z}}
]

Compute:

[
\hat{y} = \frac{1}{1+e^{-2}}
\approx \frac{1}{1+0.1353}
\approx 0.8808
]

---

### Step 2: Apply the Chain Rule

We want to find:

[
\frac{\partial L}{\partial w}
]

Using the chain rule:

[
\frac{\partial L}{\partial w}
=============================

\frac{\partial L}{\partial \hat{y}}
\cdot
\frac{\partial \hat{y}}{\partial z}
\cdot
\frac{\partial z}{\partial w}
]

---

### Step 3: Compute each derivative

#### (a) Loss derivative

For binary cross-entropy,

[
\frac{\partial L}{\partial \hat{y}}
===================================

-\frac{y}{\hat{y}}
+
\frac{1-y}{1-\hat{y}}
]

Since (y=1),

[
\frac{\partial L}{\partial \hat{y}}
===================================

-\frac{1}{0.8808}
\approx -1.1353
]

---

#### (b) Sigmoid derivative

[
\frac{\partial \hat{y}}{\partial z}
===================================

\hat{y}(1-\hat{y})
]

# [

# 0.8808(1-0.8808)

0.8808\times0.1192
\approx0.1050
]

---

#### (c) Weighted sum derivative

[
z=wx+b
]

Therefore,

[
\frac{\partial z}{\partial w}=x=2
]

---

### Step 4: Multiply the derivatives

[
\frac{\partial L}{\partial w}
=============================

(-1.1353)
\times
(0.1050)
\times
2
]

[
\approx
-0.2384
]

---

### Alternative Simplified Formula

For a sigmoid output with binary cross-entropy loss,

[
\frac{\partial L}{\partial w}
=============================

(\hat{y}-y)x
]

Substitute the values:

# [

# (0.8808-1)\times2

# (-0.1192)\times2

-0.2384
]

This matches the result obtained using the chain rule.

### Final Answer

[
\boxed{\frac{\partial L}{\partial w}\approx -0.2384}
]

The negative gradient indicates that increasing the weight slightly would reduce the loss for this training example.


QUE : 4 -->

Build a function in Python that simulates vanishing gradient by applying the sigmoid activation repeatedly to an input (e.g., 0.9) for 10 layers, and print the final output.Hint:Observe how the value shrinks as you increase the number of layers.


In [3]:
import math

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

# Function to simulate vanishing gradient
def vanishing_gradient(input_value, layers):
    output = input_value

    print("Initial Input:", output)

    for i in range(layers):
        output = sigmoid(output)
        print(f"Layer {i+1}: {output:.6f}")

    return output

# Input value and number of layers
input_value = 0.9
layers = 10

# Calculate final output
final_output = vanishing_gradient(input_value, layers)

print("\nFinal Output after", layers, "layers:", final_output)

Initial Input: 0.9
Layer 1: 0.710950
Layer 2: 0.670611
Layer 3: 0.661640
Layer 4: 0.659629
Layer 5: 0.659177
Layer 6: 0.659075
Layer 7: 0.659053
Layer 8: 0.659048
Layer 9: 0.659046
Layer 10: 0.659046

Final Output after 10 layers: 0.6590461433964991


QUE : 5 -->

Use ChatGPT or Copilot to generate Python code that demonstrates exploding gradients in a deep network by initializing weights with large values, then explain in 2-3 lines what happens to the gradients during backpropagation.

In [4]:
import numpy as np

# Reproducibility
np.random.seed(42)

# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

# Initialize large weights
weights = [10.0] * 10   # 10 layers with large weights

# Input
x = 1.0

# Forward pass
activations = [x]
z_values = []

for w in weights:
    z = w * activations[-1]
    z_values.append(z)
    activations.append(sigmoid(z))

# Backward pass (simulate gradient propagation)
gradient = 1.0

print("Gradient at each layer:")

for i in reversed(range(len(weights))):
    gradient *= weights[i] * sigmoid_derivative(z_values[i])
    print(f"Layer {i+1}: {gradient:.10f}")

Gradient at each layer:
Layer 10: 0.0004541643
Layer 9: 0.0000002063
Layer 8: 0.0000000001
Layer 7: 0.0000000000
Layer 6: 0.0000000000
Layer 5: 0.0000000000
Layer 4: 0.0000000000
Layer 3: 0.0000000000
Layer 2: 0.0000000000
Layer 1: 0.0000000000
